# Generated by Django 2.2 on 2019-04-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptiono',
            new_name='description',
        ),
    ]
