# Generated by Django 2.2 on 2019-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='website_images/Unknown.png', path='/projects/img/'),
        ),
    ]
