# Generated by Django 2.2 on 2019-04-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190407_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='website_images/Unknown.png', upload_to=''),
        ),
    ]
